apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: changed volume name from website to data
  name: rollingpods
  labels:
    app: mynginxdeploy
spec:
        #strategy:
        #type: Recreate
  replicas: 3
  selector:
    matchLabels:
      name: nginx    
  template:
    # copy pod metadata and spec here
    metadata:
      name: nginxpod
      labels:
        name: nginx
        app: rollapp
        note: rolling
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: nginx
        image: nginx:1.19.1
        # image: nginx:latest
        volumeMounts:
        - name: data
          mountPath: /usr/share/nginx/html
      volumes:
      - name: data
        emptyDir: 
