apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  imagePullSecrets:
  - name: regcred
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: website
      mountPath: /usr/share/nginx/html
  volumes:
  - name: website
    emptyDir: 
