apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: changed volume name from website to data
  name: rollingpods2
  labels:
    app: mynginxdeploy2
spec:
        #strategy:
        #type: Recreate
  replicas: 3
  selector:
    matchLabels:
      name: nginx2
  template:
    # copy pod metadata and spec here
    metadata:
      name: nginxpod2
      labels:
        name: nginx2
        app: rollapp2
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: nginx
        image: nginx:1.19.1
        # image: nginx:latest
        volumeMounts:
        - name: data
          mountPath: /usr/share/nginx/html
      volumes:
      - name: data
        persistentVolumeClaim: 
          claimName: mydynpvc
