apiVersion: v1
kind: PersistentVolume
metadata:
  name: myvol
  labels:
    type: local
spec:
  storageClassName: testing
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
