apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: true
    prometheusK8s: 
      retention: 12h 
      volumeClaimTemplate:
       spec:
         volumeMode: Filesystem
         resources:
           requests:
             storage: 5Gi
