apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-share1
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
   - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /srv/volumes/share1
    server: bernd-ttxb.vm
